package:
  name: featmf
  version: 0.1.0

source:
  path: .

requirements:
  build:
    - python
    - setuptools
    - hatchling
  run:
    - python

build:
  number: 0
  script: "python -m pip install . --no-deps --ignore-installed -vv"

about:
  home: https://github.com/TheProjectsGuy/FeatMF
  license: LGPLv3
  summary: A Feature Matching Framework
